name: CI

on:
  push:
    branches:
      - '**'

jobs:
  checks:
    name: 🧪 Shell script checks
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout repository
        uses: actions/checkout@v4

      - name: 🐰 Install bun
        uses: oven-sh/setup-bun@v2

      - name: 🧰 Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: 📦 Install dependencies
        run: bun install --frozen-lockfile

      - name: 🔍 shellcheck
        run: bun run shellcheck

      - name: 📝 syntax
        run: bun run syntax

      - name: 🔑 executable
        run: bun run executable

      - name: 👉 shebang
        run: bun run shebang

      - name: ✅ All checks passed
        run: echo "All shell script checks passed."
